name: Build Release Executables

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller streamlit pandas

    - name: Build Windows executable
      run: |
        pyinstaller scout_tracker.spec --clean --noconfirm

    - name: Create distribution package
      run: |
        # Create a clean distribution folder
        mkdir -p dist/ScoutTracker_Windows

        # Copy executable and dependencies
        cp -r dist/ScoutTracker/* dist/ScoutTracker_Windows/

        # Create launcher script
        echo '@echo off' > dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'title Scout Tracker' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'color 0A' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'cls' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo '' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo.' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    ========================================' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo         SCOUT TRACKER - Starting...' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    ========================================' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo.' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    Opening Scout Tracker in your web browser...' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo.' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    ========================================' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    KEEP THIS WINDOW OPEN while using the app' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    Close this window to stop Scout Tracker' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo    ========================================' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'echo.' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat
        echo 'ScoutTracker.exe' >> dist/ScoutTracker_Windows/START_SCOUT_TRACKER.bat

        # Create README
        echo 'SCOUT TRACKER - Windows Distribution' > dist/ScoutTracker_Windows/README.txt
        echo '======================================' >> dist/ScoutTracker_Windows/README.txt
        echo '' >> dist/ScoutTracker_Windows/README.txt
        echo 'QUICK START:' >> dist/ScoutTracker_Windows/README.txt
        echo '' >> dist/ScoutTracker_Windows/README.txt
        echo '  1. Double-click START_SCOUT_TRACKER.bat' >> dist/ScoutTracker_Windows/README.txt
        echo '  2. Wait for your web browser to open' >> dist/ScoutTracker_Windows/README.txt
        echo '  3. Keep the black window open while using the app' >> dist/ScoutTracker_Windows/README.txt
        echo '' >> dist/ScoutTracker_Windows/README.txt
        echo 'NO PYTHON INSTALLATION REQUIRED!' >> dist/ScoutTracker_Windows/README.txt
        echo '' >> dist/ScoutTracker_Windows/README.txt
        echo 'Your data is saved in the tracker_data folder.' >> dist/ScoutTracker_Windows/README.txt
        echo '' >> dist/ScoutTracker_Windows/README.txt
        echo 'For help: https://github.com/quellant/scout-tracker' >> dist/ScoutTracker_Windows/README.txt
      shell: bash

    - name: Create ZIP archive
      run: |
        cd dist
        powershell Compress-Archive -Path ScoutTracker_Windows -DestinationPath ScoutTracker_Windows.zip

    - name: Upload Windows executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScoutTracker-Windows
        path: dist/ScoutTracker_Windows.zip

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ScoutTracker_Windows.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller streamlit pandas

    - name: Build Linux executable
      run: |
        pyinstaller scout_tracker.spec --clean --noconfirm

    - name: Create distribution package
      run: |
        mkdir -p dist/ScoutTracker_Linux
        cp -r dist/ScoutTracker/* dist/ScoutTracker_Linux/

    - name: Create launcher script
      run: |
        cat > dist/ScoutTracker_Linux/start_scout_tracker.sh <<'LAUNCHER'
#!/bin/bash
clear
echo ""
echo "    ========================================"
echo "         SCOUT TRACKER - Starting..."
echo "    ========================================"
echo ""
echo "    Opening Scout Tracker in your web browser..."
echo ""
echo "    ========================================"
echo "    KEEP THIS WINDOW OPEN while using the app"
echo "    Close this window to stop Scout Tracker"
echo "    ========================================"
echo ""
./ScoutTracker
LAUNCHER
        chmod +x dist/ScoutTracker_Linux/start_scout_tracker.sh

    - name: Create README
      run: |
        cat > dist/ScoutTracker_Linux/README.txt <<'README'
SCOUT TRACKER - Linux Distribution
====================================

QUICK START:

  1. Make the launcher executable (first time only):
     chmod +x start_scout_tracker.sh

  2. Run the launcher:
     ./start_scout_tracker.sh

  3. Wait for your web browser to open

  4. Keep the terminal window open while using the app

NO PYTHON INSTALLATION REQUIRED!

Your data is saved in the tracker_data folder.

For help: https://github.com/quellant/scout-tracker
README

    - name: Create tar.gz archive
      run: |
        cd dist
        tar -czf ScoutTracker_Linux.tar.gz ScoutTracker_Linux

    - name: Upload Linux executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScoutTracker-Linux
        path: dist/ScoutTracker_Linux.tar.gz

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ScoutTracker_Linux.tar.gz

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller streamlit pandas

    - name: Build macOS executable
      run: |
        pyinstaller scout_tracker.spec --clean --noconfirm

    - name: Create distribution package
      run: |
        mkdir -p dist/ScoutTracker_macOS
        cp -r dist/ScoutTracker/* dist/ScoutTracker_macOS/

    - name: Create launcher script
      run: |
        cat > dist/ScoutTracker_macOS/start_scout_tracker.command <<'LAUNCHER'
#!/bin/bash
cd "$(dirname "$0")"
clear
echo ""
echo "    ========================================"
echo "         SCOUT TRACKER - Starting..."
echo "    ========================================"
echo ""
echo "    Opening Scout Tracker in your web browser..."
echo ""
echo "    ========================================"
echo "    KEEP THIS WINDOW OPEN while using the app"
echo "    Close this window to stop Scout Tracker"
echo "    ========================================"
echo ""
./ScoutTracker
LAUNCHER
        chmod +x dist/ScoutTracker_macOS/start_scout_tracker.command

    - name: Create README
      run: |
        cat > dist/ScoutTracker_macOS/README.txt <<'README'
SCOUT TRACKER - macOS Distribution
===================================

QUICK START:

  1. Double-click start_scout_tracker.command

  2. If you get a security warning:
     - Right-click start_scout_tracker.command
     - Choose "Open"
     - Click "Open" in the dialog

  3. Wait for your web browser to open

  4. Keep the terminal window open while using the app

NO PYTHON INSTALLATION REQUIRED!

Your data is saved in the tracker_data folder.

For help: https://github.com/quellant/scout-tracker
README

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ScoutTracker_macOS.zip ScoutTracker_macOS

    - name: Upload macOS executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScoutTracker-macOS
        path: dist/ScoutTracker_macOS.zip

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ScoutTracker_macOS.zip
